# -*- coding: utf-8 -*-
"""Brsm_final_thing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YH0QSdE1HAOvSduNnQtY4H_0H_OGQqp
"""

# Cell 1: Setup and Data Loading
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.spatial.distance import pdist, squareform
from scipy.stats import pearsonr, ttest_ind, mannwhitneyu
import warnings
warnings.filterwarnings('ignore')

sns.set(style="whitegrid")

file_path = '/content/responses (1).json'
with open(file_path, 'r') as f:
    data = json.load(f)

df = pd.DataFrame.from_dict(data['fluency-spam'], orient='index')
df.reset_index(inplace=True)
df.rename(columns={'index': 'id'}, inplace=True)

# --- sanity check ---
print(f"df shape: {df.shape}")
print(f"df columns: {list(df.columns)}")
print(f"unique subjects: {df['subject_id'].nunique() if 'subject_id' in df.columns else 'N/A'}")

# Cell 2: Process VFT Data
vft_results = []
for index, row in df.iterrows():
    subject_id = row['subject_id']
    participant_data = row['data']

    if isinstance(participant_data, list):
        for trial in participant_data:
            if trial.get('task') == 'VFT' and trial.get('trial_type') == 'html-keyboard-response':
                domain = trial.get('domain', 'unknown')

                tagged_responses_raw = trial.get('tagged_responses')
                response_times_raw = trial.get('response_times')

                if isinstance(tagged_responses_raw, str):
                    try: tagged_responses = json.loads(tagged_responses_raw)
                    except: tagged_responses = []
                elif isinstance(tagged_responses_raw, list): tagged_responses = tagged_responses_raw
                else: tagged_responses = []

                if isinstance(response_times_raw, str):
                    try: response_times = json.loads(response_times_raw)
                    except: response_times = []
                elif isinstance(response_times_raw, list): response_times = response_times_raw
                else: response_times = []

                words = [item.get('response') for item in tagged_responses
                         if isinstance(item, dict) and 'response' in item]
                word_count = len(words)
                irts = response_times
                mean_irt = np.mean(irts) if len(irts) > 0 else np.nan

                vft_results.append({
                    'subject_id': subject_id,
                    'domain': domain,
                    'word_count': word_count,
                    'mean_irt': mean_irt,
                    'words': words,
                    'irts': irts
                })

df_vft = pd.DataFrame(vft_results)

# --- sanity check ---
print(f"df_vft shape: {df_vft.shape}")
print(f"unique subjects in VFT: {df_vft['subject_id'].nunique()}")
print(f"\nTrials per domain:")
print(df_vft['domain'].value_counts())
print(f"\nword_count summary:")
print(df_vft['word_count'].describe())

# Diagnostic: practice-domain check + per-position IRT table
from collections import defaultdict

is_practice = df_vft['domain'].str.contains('practice', case=False, na=False)
print(f"Trials flagged as practice: {is_practice.sum()}  ({is_practice.sum()/len(df_vft):.0%})")
print(f"Practice domains found:    {df_vft.loc[is_practice, 'domain'].unique().tolist()}")
print(f"Subjects with a practice trial: {df_vft.loc[is_practice, 'subject_id'].nunique()}/35")

def per_position_table(vft_subset, label):
    pos_irts = defaultdict(list)
    for _, row in vft_subset.iterrows():
        for i, irt in enumerate(row['irts']):
            if 0 < irt < 30000:
                pos_irts[i + 1].append(irt)
    total = len(vft_subset)
    print(f"\n--- {label}  (n_trials = {total}) ---")
    print(f"{'Pos':>4} {'n':>5} {'%':>6} {'mean':>9} {'median':>9} {'sd':>9}")
    for pos in sorted(pos_irts.keys()):
        vals = pos_irts[pos]
        if not vals: continue
        print(f"{pos:>4d} {len(vals):>5d} {100*len(vals)/total:>5.1f}% "
              f"{np.mean(vals):>9.1f} {np.median(vals):>9.1f} {np.std(vals):>9.1f}")

per_position_table(df_vft,                     "ALL trials (incl. practice)")
per_position_table(df_vft[~is_practice],       "Non-practice trials only")

# Cell 3: Process SpAM Data
spam_results = []
for index, row in df.iterrows():
    subject_id = row['subject_id']
    participant_data = row['data']

    if isinstance(participant_data, list):
        for trial in participant_data:
            if trial.get('task') == 'SpAM':
                domain = trial.get('domain', 'unknown')
                dropped_words_raw = trial.get('droppedwords')

                if isinstance(dropped_words_raw, str):
                    try: dropped_words = json.loads(dropped_words_raw)
                    except: dropped_words = []
                elif isinstance(dropped_words_raw, list): dropped_words = dropped_words_raw
                else: dropped_words = []

                word_coords_dict = {}
                for item in dropped_words:
                    if isinstance(item, dict):
                        word = item.get('word')
                        x = item.get('x_norm')
                        y = item.get('y_norm')
                        if word is not None and x is not None and y is not None:
                            word_coords_dict[word] = {'word': word, 'x': x, 'y': y}

                word_coords = list(word_coords_dict.values())
                pairwise_distances = []

                if len(word_coords) >= 2:
                    coords = [[w['x'], w['y']] for w in word_coords]
                    words = [w['word'] for w in word_coords]
                    dists = pdist(coords, metric='euclidean')

                    k = 0
                    for i in range(len(words)):
                        for j in range(i + 1, len(words)):
                            pairwise_distances.append({
                                'word1': words[i],
                                'word2': words[j],
                                'distance': dists[k]
                            })
                            k += 1

                spam_results.append({
                    'subject_id': subject_id,
                    'domain': domain,
                    'word_count': len(word_coords),
                    'word_coords': word_coords,
                    'pairwise_distances': pairwise_distances
                })

df_spam = pd.DataFrame(spam_results)

# --- sanity check ---
print(f"df_spam shape: {df_spam.shape}")
print(f"unique subjects in SpAM: {df_spam['subject_id'].nunique()}")
print(f"\nTrials per domain:")
print(df_spam['domain'].value_counts())
print(f"\nword_count (placed words) summary:")
print(df_spam['word_count'].describe())

survey_rows = []
for _, row in df.iterrows():
    participant_data = row['data']
    subject_id = row['subject_id']
    if isinstance(participant_data, list):
        for trial in participant_data:
            if trial.get('trial_type') == 'survey-html-form':
                entry = {'subject_id': subject_id}
                for key in ['Hi_Read', 'Hi_Write', 'Hi_Speak', 'Hi_Understand']:
                    if key in trial:
                        entry[key] = trial.get(key)
                if len(entry) > 1:
                    survey_rows.append(entry)

if len(survey_rows) > 0:
    survey_df = pd.DataFrame(survey_rows).groupby('subject_id').first().reset_index()
    for col in survey_df.columns:
        if col != 'subject_id':
            survey_df[col] = pd.to_numeric(survey_df[col], errors='coerce')
    hi_cols = [c for c in survey_df.columns if c.startswith('Hi_')]
    survey_df['hi_fluency_score'] = survey_df[hi_cols].mean(axis=1) if hi_cols else np.nan
else:
    survey_df = pd.DataFrame(columns=['subject_id', 'hi_fluency_score'])

# --- sanity check ---
# --- sanity check (corrected: only use columns that actually exist) ---
available_hi_cols = [c for c in survey_df.columns if c.startswith('Hi_')]
print(f"survey_df shape: {survey_df.shape}")
print(f"Fluency dimensions found in data: {available_hi_cols}")
print(f"subjects with fluency data: {survey_df['hi_fluency_score'].notna().sum()}/35")
print(f"\nFluency score (composite) summary:")
print(survey_df['hi_fluency_score'].describe().round(2))
print(f"\nPer-dimension summary:")
print(survey_df[available_hi_cols].describe().round(2))

# Cell 5: RQ1 — Semantic Clustering
  # Do adjacent (chronological) word transitions sit closer in SpAM space
  # than randomly sampled word pairs? Non-practice trials only.

  df_vft_main  = df_vft [~df_vft ['domain'].str.contains('practice', case=False, na=False)].copy()
  df_spam_main = df_spam[~df_spam['domain'].str.contains('practice', case=False, na=False)].copy()

  paired_data = []
  for _, vft_row in df_vft_main.iterrows():
      subject, domain = vft_row['subject_id'], vft_row['domain']
      words, irts     = vft_row['words'], vft_row['irts']

      spam_match = df_spam_main[(df_spam_main['subject_id'] == subject) &
                                (df_spam_main['domain']     == domain)]
      if spam_match.empty:
          continue

      dist_lookup = {}
      for item in spam_match.iloc[0]['pairwise_distances']:
          dist_lookup[(item['word1'], item['word2'])] = item['distance']
          dist_lookup[(item['word2'], item['word1'])] = item['distance']

      for k in range(1, len(words)):
          if k < len(irts):
              dist = dist_lookup.get((words[k-1], words[k]))
              if dist is not None:
                  paired_data.append({
                      'subject_id'    : subject,
                      'domain'        : domain,
                      'word_pair'     : f"{words[k-1]}-{words[k]}",
                      'irt'           : irts[k],
                      'spam_distance' : dist
                  })

  df_paired = pd.DataFrame(paired_data)
  df_paired = df_paired[(df_paired['irt'] > 0) & (df_paired['irt'] < 30000)].dropna()

  print("="*60)
  print("RQ1: Semantic Clustering  (non-practice trials)")
  print("="*60)
  print(f"Adjacent-pair rows: {len(df_paired)}")

  # (a) Pearson r between adjacent IRT and SpAM distance
  if len(df_paired) > 2:
      r, p = pearsonr(df_paired['irt'], df_paired['spam_distance'])
      print(f"\nPearson r (adjacent IRT vs SpAM distance): r = {r:.3f}, p = {p:.4f}")

  # (b) Adjacent vs Random
  adjacent_distances = df_paired['spam_distance'].values
  all_spam_dists = []
  for _, row in df_spam_main.iterrows():
      for item in row.get('pairwise_distances', []):
          if isinstance(item, dict) and 'distance' in item:
              all_spam_dists.append(item['distance'])

  if len(all_spam_dists) >= len(adjacent_distances):
      rng = np.random.default_rng(seed=42)
      rand_sample = rng.choice(all_spam_dists, size=len(adjacent_distances), replace=False)

      t_stat, t_p = ttest_ind  (adjacent_distances, rand_sample, equal_var=False)
      u_stat, u_p = mannwhitneyu(adjacent_distances, rand_sample, alternative='two-sided')

      print(f"\nMean adjacent distance: {np.mean(adjacent_distances):.4f}")
      print(f"Mean random distance:   {np.mean(rand_sample):.4f}")
      print(f"\nWelch t-test:   t = {t_stat:.3f}, p = {t_p:.4g}")
      print(f"Mann-Whitney U: U = {u_stat:.0f}, p = {u_p:.4g}")

# Cell 6: RQ2 — Semantic Neighbourhood Density
# Are words sitting in tighter SpAM neighbourhoods retrieved faster?
# Word-level Pearson r between log(1+IRT) and mean_neighbor_dist.

# word-level IRTs
latency_rows = []
for _, row in df_vft_main.iterrows():
    min_len = min(len(row['words']), len(row['irts']))
    for i in range(min_len):
        latency_rows.append({
            'subject_id' : row['subject_id'],
            'domain'     : row['domain'],
            'word'       : row['words'][i],
            'latency_ms' : row['irts'][i]
        })
word_latency_df = pd.DataFrame(latency_rows)

# word-level SpAM coordinates
rows = []
for _, r in df_spam_main.iterrows():
    for w in r['word_coords']:
        rows.append({
            'subject_id' : r['subject_id'],
            'domain'     : r['domain'],
            'word'       : w['word'],
            'x'          : w['x'],
            'y'          : w['y']
        })
wc = pd.DataFrame(rows)

# mean neighbour distance per word (density proxy)
dens_list = []
for (s, d), g in wc.groupby(['subject_id', 'domain']):
    coords = g[['x', 'y']].values
    if len(coords) < 2:
        continue
    distmat  = squareform(pdist(coords))
    tmp = g.copy()
    tmp['mean_neighbor_dist'] = distmat.mean(axis=1)
    dens_list.append(tmp)

word_density = pd.concat(dens_list, ignore_index=True)
merged = pd.merge(word_latency_df, word_density,
                  on=['subject_id', 'domain', 'word'], how='inner')
merged = merged[(merged['latency_ms'] > 0) & (merged['latency_ms'] < 30000)].dropna()

print("="*60)
print("RQ2: Semantic Neighbourhood Density  (non-practice trials)")
print("="*60)
print(f"Word-level rows: {len(merged)}")

if len(merged) > 2:
    r_density, p_density = pearsonr(np.log1p(merged['latency_ms']),
                                    merged['mean_neighbor_dist'])
    print(f"\nPearson r  (log(1+IRT) vs mean_neighbor_dist):")
    print(f"  r = {r_density:.3f},  p = {p_density:.4g}")

# Cell 7: RQ3 — Fluency vs Retrieval Efficiency
# Subject-level correlations

print("="*60)
print("RQ3: Fluency vs Retrieval Efficiency")
print("="*60)

# --- cluster size computation ---
cluster_data = []

for (subject, domain), group in df_paired.groupby(['subject_id', 'domain']):
    distances = group['spam_distance'].tolist()
    if len(distances) == 0:
        continue

    threshold = np.median(distances)

    cluster_sizes = []
    current_size = 1

    for dist in distances:
        if dist < threshold:
            current_size += 1
        else:
            cluster_sizes.append(current_size)
            current_size = 1

    cluster_sizes.append(current_size)

    cluster_data.append({
        'subject_id': subject,
        'mean_cluster_size': np.mean(cluster_sizes)
    })

df_clusters = pd.DataFrame(cluster_data).groupby('subject_id').mean().reset_index()

# --- subject-level aggregation ---
vft_by_subject = df_vft_main.groupby('subject_id').agg(
    mean_words=('word_count', 'mean'),
    mean_irt=('mean_irt', 'mean')
).reset_index()

# merge all
subj = pd.merge(vft_by_subject, survey_df[['subject_id', 'hi_fluency_score']],
                on='subject_id', how='left')
subj = pd.merge(subj, df_clusters, on='subject_id', how='left')

valid_subj = subj.dropna(subset=['hi_fluency_score'])

print(f"Subjects with valid data: {len(valid_subj)}")

# --- correlations ---
if len(valid_subj) > 2:
    r_words, p_words = pearsonr(valid_subj['hi_fluency_score'], valid_subj['mean_words'])
    r_irt, p_irt = pearsonr(valid_subj['hi_fluency_score'], valid_subj['mean_irt'])

    print(f"\nFluency vs Total Words: r = {r_words:.3f}, p = {p_words:.4f}")
    print(f"Fluency vs Mean IRT:    r = {r_irt:.3f}, p = {p_irt:.4f}")

    valid_clusters = valid_subj.dropna(subset=['mean_cluster_size'])
    if len(valid_clusters) > 2:
        r_clust, p_clust = pearsonr(valid_clusters['hi_fluency_score'],
                                   valid_clusters['mean_cluster_size'])
        print(f"Fluency vs Cluster Size: r = {r_clust:.3f}, p = {p_clust:.4f}")

# Cell 8: Distribution of Total Words (VFT)

plt.figure(figsize=(8,6))
sns.histplot(df_vft_main['word_count'], bins=15, kde=True)

plt.title("Distribution of Total Words Generated (VFT)")
plt.xlabel("Number of Words")
plt.ylabel("Frequency")

plt.show()

# Cell 9: IRT vs Position (FIXED — no position 1 + coverage filter)

irt_data = []
for _, row in df_vft_main.iterrows():
    for i, irt in enumerate(row['irts']):
        if 0 < irt < 30000:
            irt_data.append({'Position': i+1, 'IRT_ms': irt})

df_irt = pd.DataFrame(irt_data)

# coverage
total_trials = len(df_vft_main)
coverage = df_irt.groupby('Position').size() / total_trials

# keep positions with >=50% coverage AND drop position 1
valid_positions = [p for p in coverage.index if coverage[p] >= 0.5 and p > 1]

df_irt_clean = df_irt[df_irt['Position'].isin(valid_positions)]

plt.figure(figsize=(8,6))
sns.lineplot(data=df_irt_clean, x='Position', y='IRT_ms', errorbar='sd')

plt.title("Average Inter-Response Time by Word Position (Filtered)")
plt.xlabel("Word Position")
plt.ylabel("IRT (ms)")

plt.show()

# Cell 10: Semantic Distance vs Retrieval Time (LOG FIX)

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=merged,
    x='mean_neighbor_dist',
    y=np.log1p(merged['latency_ms']),
    alpha=0.4
)

sns.regplot(
    data=merged,
    x='mean_neighbor_dist',
    y=np.log1p(merged['latency_ms']),
    scatter=False
)

plt.title("Semantic Distance vs Retrieval Time (log scale)")
plt.xlabel("Mean Neighbor Distance")
plt.ylabel("log(1 + IRT)")

plt.show()

# Cell 11: Early vs Late Words

early = []
late = []

for _, row in df_vft_main.iterrows():
    for i, irt in enumerate(row['irts']):
        if 0 < irt < 30000:
            if i < 5:
                early.append(irt)
            else:
                late.append(irt)

df_box = pd.DataFrame({
    'IRT': early + late,
    'Group': ['Early']*len(early) + ['Late']*len(late)
})

plt.figure(figsize=(8,6))
sns.boxplot(data=df_box, x='Group', y='IRT')

plt.title("Retrieval Speed: Early vs Late Words")
plt.ylabel("IRT (ms)")

plt.show()

plt.figure(figsize=(6,6))

plt.scatter(x, y)

for i, label in enumerate(labels):
    plt.text(x[i], y[i], label, fontsize=9, ha='right', va='bottom')

plt.title(f"SpAM Layout (Subject {sample['subject_id']}, {sample['domain']})")

# ADD THESE 👇
plt.xlabel("Normalized X Position (participant-defined)")
plt.ylabel("Normalized Y Position (participant-defined)")

plt.xlim(0,1)
plt.ylim(0,1)

plt.margins(0.05)

plt.show()



